### ISSUE TITLE
IIIF info.json identifier encoding issue - %2F rewritten as %252F for image service @id

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/purl#575] opened 2022-05-26 00:24 UTC
[Not sure if this is the right repo for this ticket - please feel free to move, might be more appropriate in stacks?]

![Screen Shot 2022-05-25 at 5 25 48 PM](https://user-images.githubusercontent.com/796990/170390667-d0acc94c-13f6-45e9-9506-9560cbb90c81.png)

In an example like the one above (from https://purl.stanford.edu/xw767xx9767/iiif/manifest), the image service @id in the presentation API is correctly encoded with a %2F separating the druidID from the imageID as part of the "identifier" block of the URL. However, resolving that URL (like `https://stacks.stanford.edu/image/iiif/xw767xx9767%2Fxw767xx9767_0001`) results in a rewriting of the %2F encoding to %252F (like `https://stacks.stanford.edu/image/iiif/xw767xx9767%252Fxw767xx9767_0001/info.json`).

The @id published by the image service (`"@id": "https://stacks.stanford.edu/image/iiif/xw767xx9767/xw767xx9767_0001"`) does not contain the %2F encoding which is required by the spec (https://iiif.io/api/image/2.1/#uri-encoding-and-decoding).

So - it seems like there might be two issues at play here:
*  a discrepancy between our presentation API (which correctly codes the internal slash in the identifier section) and our image API - if we follow the service @id from the manifest, the %2F gets rewritten to %252F (there was an old Apache rewrite module bug that did this - could this be a similar issue?)
* an issue in our image API implementation that is not correctly replacing the internal slash within the identifier with a %2F in the @id for the info.json document

All 3 URL structures return the info.json document:
* https://stacks.stanford.edu/image/iiif/xw767xx9767%2Fxw767xx9767_0001/info.json
* https://stacks.stanford.edu/image/iiif/xw767xx9767%252Fxw767xx9767_0001/info.json
* https://stacks.stanford.edu/image/iiif/xw767xx9767/xw767xx9767_0001/info.json

Preferably:
* the service @id in the manifest would resolve without having the %2F rewritten as %252F
* and would return an info.json document whose @id includes the %2F encoding specified in https://iiif.io/api/image/2.1/#uri-encoding-and-decoding

**Comment by anarchivist** [comment] 2022-05-26 19:07
Thanks for writing this up, @blalbrit. I believe this is same issue, or is related to sul-dlss/stacks#864.

**Comment by thatbudakguy** [comment] 2022-05-27 17:47
Agree this is is a duplicate of https://github.com/sul-dlss/stacks/issues/864, but this context & detailed explanation is extremely useful. Going to quote some of @blalbrit's explanation on that issue for added context.

**Comment by cbeer** [comment] 2022-08-29 15:15
Fixed by https://github.com/sul-dlss/purl/pull/560?

**Closed by cbeer** 2022-08-29 15:15 UTC
Labels: duplicate
