### ISSUE TITLE
form submission sends two duplicate messages 

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/purl#487] opened 2021-05-04 22:38 UTC
Recently (in the last week or so), we notice that a submission to the purl feedback form results in two, duplicate messages are received by members of the purl-feedback list. As far as I am aware, nothing has changed on the list management side that would result in duplicate messages.

is it a bug in the form?

**Comment by mjgiarlo** [comment] 2021-06-03 23:56
@hannahfrost I have not been able to reproduce this either locally or in stage, and I have a sneaking suspicion that this is due to what I just wrote up in #496. Plausible?

**Comment by hannahfrost** [comment] 2021-06-04 00:13
@mjgiarlo Maybe? Not sure. Literally every message sent via this form, regardless of user, since I reported the bug has resulted in double messages. I just tested it in prod and got two messages again after a single click of the submit button.

**Comment by mjgiarlo** [comment] 2021-06-04 00:19
@hannahfrost ok! thanks, I'll have another look.

**Comment by hannahfrost** [comment] 2021-06-04 15:40
@mjgiarlo Not sure if this is related, but Josh Schneider submitted feedback via Spotlight yesterday and I received duplicate messages.

**Comment by mjgiarlo** [comment] 2021-06-04 15:49
> @mjgiarlo Not sure if this is related, but Josh Schneider submitted feedback via Spotlight yesterday and I received duplicate messages.
> 

Oh, huh. Thanks for sharing that! Do you think you could forward me a couple dupes so I can inspect the headers?

**Comment by hannahfrost** [comment] 2021-06-04 16:17
@mjgiarlo Sent you two examples from the two forms (purl and exhibits)

**Comment by anarchivist** [comment] 2021-06-04 19:23
Looks like the duplicate messages have distinct `Message-ID` headers, e.g. for Hannah's "testing testing disregard" feedback"

* `Message-ID: <60b96fe1edcc6_28aa65e0100036@sul-purl-prod-b.stanford.edu.mail>`
* `Message-ID: <60b96fe1ec998_5ccc65e0676b4@sul-purl-prod-a.stanford.edu.mail>`

**Comment by mjgiarlo** [comment] 2021-06-04 19:53
@hannahfrost @anarchivist Thanks, you two. I'll take another look on Monday AM.

**Comment by mjgiarlo** [comment] 2021-06-07 17:11
@hannahfrost do you know if the double posts are happening in stage as well? Or just prod? Given what @anarchivist posted above, my hunch is they are only happening in prod.

**Comment by hannahfrost** [comment] 2021-06-07 17:16
@mjgiarlo I do not know what is happening in stage, haven’t tried.

—
Hannah Frost | Assistant Director for Digital Services
Stanford Libraries<https://library.stanford.edu/> | Digital Library Systems and Services
Lathrop Library 384
E: ***@***.******@***.***> | C: (650) 799-1352
Pronouns: she/her

On Jun 7, 2021, at 10:12 AM, Michael J. Giarlo ***@***.******@***.***>> wrote:



@hannahfrost<https://github.com/hannahfrost> do you know if the double posts are happening in stage as well? Or just prod? Given what @anarchivist<https://github.com/anarchivist> posted above, my hunch is they are only happening in prod.

**Comment by andrewjbtw** [comment] 2021-06-07 17:19
I don't think emails are coming through to the list at all from stage. I've used the feedback form there and nothing has appeared on the list.

**Comment by mjgiarlo** [comment] 2021-06-07 17:34
@andrewjbtw @hannahfrost It looks like purl-stage is configured to send feedback form messages to `purl@jirasul.stanford.edu`. No idea if that's what it should be doing, though, or if that's even wired up correctly.

**Comment by mjgiarlo** [comment] 2021-06-08 15:13
@hannahfrost a potential fix has been deployed to all envs. Would you mind tossing a test message at purl prod and letting us know what comes through?

**Comment by hannahfrost** [comment] 2021-06-08 15:41
@mjgiarlo Looks like it is fixed for purl-feedback and exhibits-feedback. Just one message came through with each form submission. Thanks very much for that!

As far as purl-stage goes, purl@jirasul is not a thing, so would be best to align it with how it is set up on prod, but this is also not particularly pressing.

**Closed** 2021-06-08 15:41 UTC

**Comment by mjgiarlo** [comment] 2021-06-08 16:35
@hannahfrost Sure! Should purl-stage messages be routed to the same list? If so, I guess you'll be able to tell whether a message is from prod or stage judging by the URL in the message. Is that OK? 

This is like a five-minute thing, so NBD either way.
